[config]
model = "gpt-4o-2024-11-20"
log_level = "debug"
verbosity_level = 2
[pr_reviewer]
inline_code_comments = true
[pr_code_suggestions]
summarize = false
auto_extended_mode = true
[github_action_config]
auto_describe = false
auto_improve = true
auto_review = true