[config]
model = "gpt-3.5-turbo"
log_level = "debug"

[pr_reviewer]
auto_review = true
review_on_pr_open = true
review_on_push = true
inline_code_comments = true
num_code_suggestion = 5
enable_review_labels_effort=false

[github_action_config]
auto_describe = false
auto_improve = false