name : PR Review by PR Agent

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

jobs:
  pr-review-job:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      issues: write
    steps:
      - name: Run PR Review by PR Agent
        uses: docker://codiumai/pr-agent:0.28-github_action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #PROVIDER: openai
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          CONFIG.MODEL: "gpt-3.5-turbo"
          LOG_LEVEL: DEBUG
          # GITHUB_ACTION_CONFIG.AUTO_DESCRIBE: false
          #OPENAI_API_BASE: "https://api.openai.com/v1"